apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptograph-service
  labels:
    app: grpc-microservice-sample
spec:
  selector:
    matchLabels:
      app: cryptograph-service
  template:
    metadata:
      labels:
        app: cryptograph-service
    spec:
      containers:
        - name: cryptograph-service
          imagePullPolicy: Never
          image: docker.io/hsuliz/gms-cryptograph-service:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cryptograph-service
spec:
  selector:
    app: cryptograph-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
