apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: grpc-microservice-sample
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          imagePullPolicy: Never
          image: docker.io/hsuliz/gms-order-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: GRPC_ADDRESS
              value: cryptograph-service
            - name: GRPC_PORT
              value: "80"
            - name: JAVA_OPTS
              value: -XX:UseSVE=0
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
