// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/cryptograph.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CryptographService_DecodeText_FullMethodName = "/CryptographService/DecodeText"
)

// CryptographServiceClient is the client API for CryptographService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptographServiceClient interface {
	DecodeText(ctx context.Context, in *DecodeTextRequest, opts ...grpc.CallOption) (*DecodeTextResponse, error)
}

type cryptographServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptographServiceClient(cc grpc.ClientConnInterface) CryptographServiceClient {
	return &cryptographServiceClient{cc}
}

func (c *cryptographServiceClient) DecodeText(ctx context.Context, in *DecodeTextRequest, opts ...grpc.CallOption) (*DecodeTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecodeTextResponse)
	err := c.cc.Invoke(ctx, CryptographService_DecodeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptographServiceServer is the server API for CryptographService service.
// All implementations must embed UnimplementedCryptographServiceServer
// for forward compatibility.
type CryptographServiceServer interface {
	DecodeText(context.Context, *DecodeTextRequest) (*DecodeTextResponse, error)
	mustEmbedUnimplementedCryptographServiceServer()
}

// UnimplementedCryptographServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCryptographServiceServer struct{}

func (UnimplementedCryptographServiceServer) DecodeText(context.Context, *DecodeTextRequest) (*DecodeTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeText not implemented")
}
func (UnimplementedCryptographServiceServer) mustEmbedUnimplementedCryptographServiceServer() {}
func (UnimplementedCryptographServiceServer) testEmbeddedByValue()                            {}

// UnsafeCryptographServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptographServiceServer will
// result in compilation errors.
type UnsafeCryptographServiceServer interface {
	mustEmbedUnimplementedCryptographServiceServer()
}

func RegisterCryptographServiceServer(s grpc.ServiceRegistrar, srv CryptographServiceServer) {
	// If the following call pancis, it indicates UnimplementedCryptographServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CryptographService_ServiceDesc, srv)
}

func _CryptographService_DecodeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecodeTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptographServiceServer).DecodeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CryptographService_DecodeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptographServiceServer).DecodeText(ctx, req.(*DecodeTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CryptographService_ServiceDesc is the grpc.ServiceDesc for CryptographService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CryptographService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CryptographService",
	HandlerType: (*CryptographServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecodeText",
			Handler:    _CryptographService_DecodeText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cryptograph.proto",
}
